### ISSUE TITLE
Log authentication attempts

### ISSUE THREAD

**Issue by alberto-coolshop** [hslavich/OneloginSamlBundle#18]
Is there any way to be able to log every login attempt in a secondary table?

**Comment by hslavich** [comment]
This bundle doesn't provide that functionality. I think you need to create some listeners in order to log login attempts.
More info: http://symfony.com/doc/current/components/security/authentication.html#authentication-events
http://symfony.com/doc/current/cookbook/event_dispatcher/event_listener.html
Maybe that log is something that you wish to have in your identity provider.
