### ISSUE TITLE
[Question] Symfony 6 and the new bundle

### ISSUE THREAD

**Issue by back-2-95** [hslavich/OneloginSamlBundle#191]
So if I understood correctly, https://github.com/nbgrp/onelogin-saml-bundle is meant for Symfony 6+
and it's by same person(s) as this one?

In other words, this bundle will stay as Symfony 5 (and older) bundle?

**Comment by a-menshchikov** [comment]
@back-2-95 thanks for your question.
Today the correct answer is "Yes" and "Yes".

nb:group's bundle was developed by me and lately I've been helping Hernán to develop this bundle. Therefore, it would be correct to say that the new bundle made by the same person as this one.

I have no plans to add support for Symfony 6 in this bundle at the moment, because I'm absolutely sure that use of the new one give everyone much more advantages than staying with this bundle.

**Comment by back-2-95** [comment]
I will update my Symfony app to 6 with https://github.com/nbgrp/onelogin-saml-bundle
Thanks for the all the great work!
