### ISSUE TITLE
Typed property

### ISSUE THREAD

**Issue by lolo-orsu** [hslavich/OneloginSamlBundle#196]
```
<?php

namespace Hslavich\OneloginSamlBundle\Security\User;

use Symfony\Component\Security\Core\User\UserInterface;

interface SamlUserFactoryInterface
{
    /**
     * Creates a new User object.
     */
    public function createUser(string $username, array $attributes = []): UserInterface;
}
```

**Comment by a-menshchikov** [comment]
Hello @LaurentSanson 
It cannot be done, because the deprecated `Hslavich\OneloginSamlBundle\Security\Authentication\Provider\SamlProvider` still pass the `TokenInterface` object into `createUser`:
https://github.com/hslavich/OneloginSamlBundle/blob/201a447daf918e8a7c4feff4761fe35096fb695c/Security/Authentication/Provider/SamlProvider.php#L83-L91
